FROM node:22.22.0-alpine3.23

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --omit=dev
COPY ./src ./src
COPY ./public ./public
COPY ./start.sh ./start.sh
RUN chmod +x ./start.sh

#CMD ["bin/sh" "-c", "npx wait-port metadata:80 && npx wait-port history:80 && npm start"]
CMD ["./start.sh"]
