FROM node:22.22.0-alpine3.23

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --omit=dev
COPY ./src ./src
COPY ./start.sh ./start.sh
RUN chmod +x ./start.sh

#CMD ["sh" "-c", "npx wait-port rabbit:5672 && npm start"]

CMD ["./start.sh"]
