FROM node:22.22.0-alpine3.23

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --omit=dev
COPY ./src ./src
RUN mkdir ./storage
COPY ./start.sh ./start.sh
RUN chmod +x ./start.sh

#CMD [ "npm" "start"]
CMD ["./start.sh"]
